config/routes.rb
Rails.application.routes.draw do
  root 'stocks#index'

  resources :stocks, only: %i(new create show index)
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates(* %i(
    name
    price
    quantity
    percentage
    years
  ), presence: true
           )
  validates(* %i(
    price
    quantity
    percentage
    years
  ), numericality: { greater_than_or_equal_to: 0 }
           )

  def total_value
    @total_value ||= (price * quantity).round(2)
  end

  def stock_values_each_year
    @stock_values_each_year ||= StockValuesCalculator.new(self).yearly_values
  end
end

app/models/stock_values_calculator.rb
class StockValuesCalculator
  def initialize(stock_data)
    @stock_data = stock_data
  end

  def yearly_values
    values = []
    values << [0, @stock_data.total_value]

    (1..@stock_data.years).inject(@stock_data.total_value) do |total, year|
      yearly_value = total_stock_value_with_yield(total)
      values << [year, yearly_value]
      yearly_value
    end
    values
  end

  private

  def total_stock_value_with_yield(total_value)
    (total_value + ((total_value * @stock_data.percentage) / 100)).round(2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  STOCK_PARAMS = %i(name price quantity percentage years)

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to stock_path(@stock)
    else
      render 'new'
    end
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def index
    @stocks = Stock.all
  end

  private

  def stock_params
    params.require(:stock).permit(*STOCK_PARAMS)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_with_two_decimals(number)
    format('%.2f', number)
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
  def values_array_for_chart_to_json(stock)
    stock.stock_values_each_year.map(&:last)
      .unshift(stock.name).to_json
  end
end

app/views/home/index.html.haml
- content_for :title, 'Stock productivity calculator'

.row
  .large-12.columns
    = button_to 'Enter new stock', new_stock_path, { class: 'button', method: :get }

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Stock Productivity Calculation"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %nav.top-bar{"data-topbar" => "", :role => "navigation"}
      %ul.title-area
        %li.name
          %h1
            = link_to 'Stock productivity calculator', root_path
    .main-content
      = yield

app/views/stocks/index.html.haml
- content_for :title, 'Stock productivity calculator'

.row
  .large-12.columns
    %table
      %thead
        %tr
          %th Name
          %th Price
          %th Quantity
          %th Percentage
          %th Years
      %tbody
        - @stocks.each do |stock|
          %tr
            %td= link_to stock.name, stock_path(stock)
            %td= number_with_two_decimals(stock.price)
            %td= stock.quantity
            %td= number_with_two_decimals(stock.percentage)
            %td= stock.years

.row
  .large-12.columns
    = button_to 'Enter new stock', new_stock_path, { class: 'button', method: :get }

app/views/stocks/new.html.haml
- content_for :title, 'Enter stock details'

.row
  .large-4
    = form_for @stock do |f|
      - if @stock.errors.any?
        .alert-box.info.radius{ data: { alert: true } }
          %h3 Fix following errors:
          %ul
            - @stock.errors.full_messages.each do |msg|
              %li= msg
      %fieldset
        %legend Enter stock details

        = f.label :name
        = f.text_field :name

        = f.label :price
        = f.text_field :price

        = f.label :quantity
        = f.text_field :quantity

        = f.label :percentage
        = f.text_field :percentage

        = f.label :years
        = f.text_field :years

        = f.submit 'Calculate', class: 'button small success'

app/views/stocks/show.html.haml
- content_for :title, 'Calculation result'

.row
  .large-2.columns
    %table
      %tbody
        %tr
          %td= "Name: #{@stock.name}"
        %tr
          %td= "Price: #{number_with_two_decimals(@stock.price)}"
        %tr
          %td= "Quantity: #{@stock.quantity}"
        %tr
          %td= "Percentage: #{number_with_two_decimals(@stock.percentage)}"
        %tr
          %td= "Years: #{@stock.years}"
  .large-10.columns
    %table#stock_values_table
      %tbody
        %tr
          %td Year
          - @stock.stock_values_each_year.map(&:first).each do |year|
            %td{ id: "year_#{year}" }= year
        %tr
          %td Stock value
          - @stock.stock_values_each_year.each do |year, price|
            %td{ id: "price_#{year}" }= number_with_two_decimals(price)
.row
  .large-12.columns
    #stockChart{ data: { values: values_array_for_chart_to_json(@stock) } }
.row
  .large-12.columns
    = link_to 'Back', :back, class: 'button small success'